"""empty message

Revision ID: 44678b139018
Revises: 50260c8c0836
Create Date: 2021-03-23 21:27:25.722306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44678b139018'
down_revision = '50260c8c0836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('desc_seeking', sa.String(length=200), nullable=True))
    op.add_column('Artist', sa.Column('talent_seeking', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'talent_seeking')
    op.drop_column('Artist', 'desc_seeking')
    # ### end Alembic commands ###
