"""empty message

Revision ID: a13280b317f6
Revises: ab975ccae01f
Create Date: 2021-03-28 20:55:41.918986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13280b317f6'
down_revision = 'ab975ccae01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'website_link', nullable=False, new_column_name='website')
    op.alter_column('venue', 'website_link', nullable=False, new_column_name='website')
    # ### end Alembic commands ###

    



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'website')
    op.add_column('artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
